
replicas: 3
minimumMasterNodes: 2




volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi



resources:
  requests:
    cpu: "200m"
    memory: "500Mi"
  limits:
    cpu: "1000m"
    memory: "2Gi"


readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 3
  timeoutSeconds: 5
