apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
 
  labels:
    app: prometheus
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
    spec:
      containers:
      - name: prometheus
        image: quay.io/prometheus/prometheus:v2.0.0
        imagePullPolicy: IfNotPresent
        args:
          - '--storage.tsdb.retention=6h'
          - '--storage.tsdb.path=/prometheus'
          - '--config.file=/etc/prometheus/prometheus.yml'
        command:
        - /bin/prometheus
        ports:
        - name: web
          containerPort: 9090
        resources:     
            requests:
              memory: 500Mi
              cpu: 300m
            limits:
              memory: 2000Mi
              cpu: "750m" 
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
        - name: data
          mountPath: /prometheus
        - name: prometheus-volume
          mountPath: "/prometheus/data"


      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: prometheus-volume
        persistentVolumeClaim:
             claimName: prom-pvc
      - name: config-volume
        configMap:
          name: prometheus-config
      - name: data
        emptyDir: {}