    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
     name: prom-pvc
   #  namespace: monitoring-gessa
    
    spec:
     accessModes:
     - ReadWriteOnce
     resources:
      requests:
       storage: 5Gi